name: auto update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Auto-update data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          args: install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

      - name: Installation
        run: |
          yarn install
          yarn install --dev

      - name: Debug
        run: |
          ls -l
          ls -l src

      - name: Generate JSON files by Puppeteer
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: 'true'
        with:
          args: yarn run start

      - name: Commit files to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: artifacts
          branch: data
